In [1]:
import tensorflow as tf
import numpy as np

In [2]:
filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [4]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [5]:
record_defaults = [[0.],[0.],[0.],[0.]]
data = tf.decode_csv(value, record_defaults=record_defaults)

In [9]:
train_x_batch, train_y_batch = tf.train.batch([data[0:-1], data[-1:]], batch_size=10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [10]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [11]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [12]:
hypothesis = tf.matmul(X, W) + b

In [13]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [15]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [16]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [17]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [18]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0:
        print(step, "Cost : ", cost_val, "\nPrediction\n", hy_val)

0 Cost :  11636.557 
Prediction
 [[38.749977]
 [59.872448]
 [51.916103]
 [59.29681 ]
 [46.68918 ]
 [40.219135]
 [44.744953]
 [33.282303]
 [62.40236 ]
 [65.07447 ]]
10 Cost :  46.45983 
Prediction
 [[146.33937]
 [189.15839]
 [179.31767]
 [198.04271]
 [145.28754]
 [112.9023 ]
 [148.60252]
 [110.27876]
 [183.21814]
 [176.96791]]
20 Cost :  51.186287 
Prediction
 [[147.09007]
 [190.01363]
 [180.18529]
 [198.97935]
 [145.9349 ]
 [113.36135]
 [149.30457]
 [110.8019 ]
 [183.99643]
 [177.66635]]
30 Cost :  50.866753 
Prediction
 [[147.11974 ]
 [190.00227 ]
 [180.19899 ]
 [198.98604 ]
 [145.92134 ]
 [113.33315 ]
 [149.3105  ]
 [110.809006]
 [183.96483 ]
 [177.61467 ]]
40 Cost :  50.512283 
Prediction
 [[147.14442]
 [189.98512]
 [180.20688]
 [198.98645]
 [145.9034 ]
 [113.30178]
 [149.31175]
 [110.81264]
 [183.92792]
 [177.55817]]
50 Cost :  50.16043 
Prediction
 [[147.16896 ]
 [189.96797 ]
 [180.2147  ]
 [198.9868  ]
 [145.88547 ]
 [113.270515]
 [149.31297 ]
 [110.81626 ]
 [183.89114 ]
 [177.50

720 Cost :  31.98389 
Prediction
 [[148.6025  ]
 [188.95534 ]
 [180.66469 ]
 [199.01495 ]
 [144.81406 ]
 [111.44793 ]
 [149.41472 ]
 [111.085396]
 [181.74568 ]
 [174.24895 ]]
730 Cost :  31.779282 
Prediction
 [[148.62105]
 [188.94206]
 [180.67041]
 [199.01544]
 [144.79985]
 [111.42441]
 [149.41646]
 [111.08973]
 [181.718  ]
 [174.20738]]
740 Cost :  31.576141 
Prediction
 [[148.63951]
 [188.92885]
 [180.6761 ]
 [199.0159 ]
 [144.78568]
 [111.40097]
 [149.41823]
 [111.09405]
 [181.6904 ]
 [174.16597]]
750 Cost :  31.374577 
Prediction
 [[148.65788]
 [188.91565]
 [180.68175]
 [199.01636]
 [144.77155]
 [111.37763]
 [149.41998]
 [111.09839]
 [181.66292]
 [174.12474]]
760 Cost :  31.174763 
Prediction
 [[148.67622]
 [188.90253]
 [180.68741]
 [199.01685]
 [144.75749]
 [111.35439]
 [149.42177]
 [111.10272]
 [181.63557]
 [174.08374]]
770 Cost :  30.976269 
Prediction
 [[148.69446]
 [188.88943]
 [180.69302]
 [199.0173 ]
 [144.74345]
 [111.33123]
 [149.42352]
 [111.10706]
 [181.6083 ]
 [174.042

1210 Cost :  23.619678 
Prediction
 [[149.42763]
 [188.359  ]
 [180.91606]
 [199.03864]
 [144.17073]
 [110.4019 ]
 [149.506  ]
 [111.30296]
 [180.51428]
 [172.41339]]
1220 Cost :  23.480042 
Prediction
 [[149.44281]
 [188.34792]
 [180.92064]
 [199.03914]
 [144.15866]
 [110.38269]
 [149.50795]
 [111.3075 ]
 [180.49165]
 [172.37993]]
1230 Cost :  23.34137 
Prediction
 [[149.45792 ]
 [188.33685 ]
 [180.92516 ]
 [199.03963 ]
 [144.14662 ]
 [110.36353 ]
 [149.5099  ]
 [111.312035]
 [180.4691  ]
 [172.3466  ]]
1240 Cost :  23.203918 
Prediction
 [[149.47299 ]
 [188.32587 ]
 [180.9297  ]
 [199.04013 ]
 [144.13466 ]
 [110.344475]
 [149.51189 ]
 [111.31657 ]
 [180.44667 ]
 [172.31345 ]]
1250 Cost :  23.067423 
Prediction
 [[149.48799 ]
 [188.31491 ]
 [180.9342  ]
 [199.04063 ]
 [144.12271 ]
 [110.325485]
 [149.51384 ]
 [111.32111 ]
 [180.42432 ]
 [172.28041 ]]
1260 Cost :  22.93193 
Prediction
 [[149.50291]
 [188.30396]
 [180.93866]
 [199.0411 ]
 [144.1108 ]
 [110.30657]
 [149.5158 ]
 [111.3256

1880 Cost :  16.273636 
Prediction
 [[150.3206 ]
 [187.69841]
 [181.17955]
 [199.07265]
 [143.44441]
 [109.27324]
 [149.64171]
 [111.60908]
 [179.18556]
 [170.4684 ]]
1890 Cost :  16.189884 
Prediction
 [[150.33217]
 [187.68971]
 [181.18289]
 [199.07317]
 [143.43474]
 [109.25863]
 [149.64378]
 [111.61365]
 [179.16835]
 [170.4435 ]]
1900 Cost :  16.106777 
Prediction
 [[150.34372 ]
 [187.68106 ]
 [181.18623 ]
 [199.07367 ]
 [143.4251  ]
 [109.244064]
 [149.64586 ]
 [111.61821 ]
 [179.15121 ]
 [170.41873 ]]
1910 Cost :  16.024214 
Prediction
 [[150.35522]
 [187.67242]
 [181.18954]
 [199.07417]
 [143.41548]
 [109.22956]
 [149.64792]
 [111.62278]
 [179.13412]
 [170.39404]]
1920 Cost :  15.942348 
Prediction
 [[150.36667]
 [187.6638 ]
 [181.19286]
 [199.07469]
 [143.4059 ]
 [109.21512]
 [149.65   ]
 [111.62733]
 [179.11714]
 [170.36948]]
1930 Cost :  15.861053 
Prediction
 [[150.37807]
 [187.65523]
 [181.19612]
 [199.0752 ]
 [143.39633]
 [109.20074]
 [149.65207]
 [111.63189]
 [179.1002 ]
 [

In [19]:
coord.request_stop()
coord.join(threads)