In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

In [4]:
nb_class = 3

In [7]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, 
                                    units=nb_class, use_bias=True))

In [8]:
tf.model.add(tf.keras.layers.Activation('softmax'))

In [9]:
tf.model.compile(loss='categorical_crossentropy',
                 optimizer=tf.keras.optimizers.SGD(lr=0.1),
                metrics=['accuracy'])

In [10]:
tf.model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [11]:
history = tf.model.fit(x_data, y_data, epochs=2000, verbose=0)

In [13]:
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

[[6.5853433e-03 9.9340469e-01 9.9247418e-06]] [1]


In [14]:
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

[[0.8417788  0.14212981 0.01609141]] [0]


In [15]:
c = tf.model.predict(np.array([[1,1,0,1]]))
c_onehot = tf.model.predict_classes(np.array([[1,1,0,1]]))
print(c, c_onehot)

[[1.4958879e-08 3.5970093e-04 9.9964023e-01]] [2]


/Users/kyh/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [16]:
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], 
                                 [1, 1, 0, 1]]))
all_onehot = tf.model.predict_classes(np.array([[1, 11, 7, 9],
                                                [1, 3, 4, 3], 
                                                [1, 1, 0, 1]]))
print(all, all_onehot)

[[6.5853191e-03 9.9340481e-01 9.9247427e-06]
 [8.4177876e-01 1.4212984e-01 1.6091397e-02]
 [1.4958879e-08 3.5970093e-04 9.9964023e-01]] [1 0 2]
